<?php $messages = $this->flashMessenger()->getCurrentSuccessMessages();?>
<?php if (!empty($messages)) { 
    echo $this->alertBlock(implode('<br />', $messages), 'alert-success'); 
} ?>
<?php $messages = $this->flashMessenger()->getCurrentErrorMessages();?>
<?php if (!empty($messages)) { 
    echo $this->alertBlock(implode('<br />', $messages), 'alert-danger'); 
} ?>
<?php
// Remember to clear messages after displaying them
use Zend\Mvc\Controller\Plugin\FlashMessenger;
$this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_ERROR);
$this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_SUCCESS);
?>