<div class="field">
    <?php 
    echo $this->formLabel($this->form->get($this->field));
    if (isset($this->inputAttributes) && is_array($this->inputAttributes)) {
        echo $this->formInput($this->form->get($this->field)->setAttributes($this->inputAttributes));
    } else {
        echo $this->formInput($this->form->get($this->field)); 
    }
    $messages = $this->form->getMessages();
    if (isset($messages[$this->field])) {
        echo '<br />'.$this->alertBlock(implode('<br />', $messages[$this->field]), 'alert-danger');
    } 
    ?>
    
</div>