<?php
switch (true) {
    case ($this->state === 1):
?>
<label class="label label-success"><?php echo $this->translate('published'); ?></label>
<?php
        break;
    case ($this->state === 0):
?>
<label class="label label-inverse"><?php echo $this->translate('unpublished'); ?></label>
<?php
        break;
    case ($this->state === 2):
?>
<label class="label label-important"><?php echo $this->translate('sold'); ?></label>
<?php
        break;
    case ($this->state === 3):
?>
<label class="label label-important"><?php echo $this->translate('traded'); ?></label>
<?php
        break;
    default:
        break;
}