<div class="user-profile text-center">
    <?php $user = $this->user; ?>
    
    <img class="img-polaroid" src="http://www.gravatar.com/avatar/<?php echo md5(trim($user->email)); ?>?s=100" />
    
    <?php if ($user->display_name != "") { ?>
    <h4 class="text-center"><?php echo $user->display_name; ?></h4>
    <?php } ?>
    <i class="icon-envelope"></i>&nbsp;<?php echo $user->email; ?>
    <br /><br />
    <a href="<?php echo $this->url('user', array('action' => 'edit', 'id' => $user->user_id), array ('query' => array('redirect' => $this->url('stuff', array('action' => 'index', 'user_id' => $user->user_id)))));?>" class="btn" target="_blank">
    <?php echo $this->translate('Edit Profile'); ?>
    </a>
</div>