<div class="user-profile text-center">
    <?php $user = $this->user; ?>
    
    <img class="img-polaroid" src="http://www.gravatar.com/avatar/<?php echo md5(trim($user->email)); ?>?s=100" />
    
    <?php if ($user->display_name != "") { ?>
    <h4 class="text-center">
        <a href="<?php echo $this->stuffUserLink($user->user_id); ?>"
            title="<?php echo $this->translate('Profile Page'); ?>">
            <?php echo $user->display_name; ?>
        </a>
    </h4>
    <?php } ?>
    <i class="icon-envelope"></i>&nbsp;<?php echo $user->email; ?>
    <?php if ($user == $this->identity()) { ?>
    <br /><br />
    <a href="<?php echo $this->url('user', array('action' => 'edit', 'id' => $user->user_id), array ('query' => array('redirect' => $this->stuffUserLink($user->user_id))));?>" class="btn" target="_blank">
    <?php echo $this->translate('Edit Profile'); ?>
    <?php } ?>
    </a>
</div>