<!DOCTYPE html>
<html>
<head>
	<link type="text/css" rel="stylesheet" href="demo/css/application.css">

  	<script type="text/javascript" src="demo/js/jquery.min.js"></script>
  	<script type="text/javascript" src="lib/jquery.raty.min.js"></script>

  	<link href="/favicon.ico" rel="shortcut icon" type="image/x-icon">
</head>
<body>
<?php $this->headTitle($this->translate('Vote This User'), 'PREPEND'); ?>
<h1><i class="iconbig-note-write"></i>&nbsp;<?php echo $this->translate('Vote This User'); ?></h1>

<?php $messages = $this->flashMessenger()->getCurrentSuccessMessages();?>
<?php if (!empty($messages)) { 
    echo $this->alertBlock(implode('<br />', $messages), 'alert-success'); 
} ?>
<?php $messages = $this->flashMessenger()->getCurrentErrorMessages();?>
<?php if (!empty($messages)) { 
    echo $this->alertBlock(implode('<br />', $messages), 'alert-danger'); 
} ?>
<?php
// Remember to clear messages after displaying them
use Zend\Mvc\Controller\Plugin\FlashMessenger;
$this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_ERROR);
$this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_SUCCESS);
?>
<?php $messages = $form->getMessages(); // Error messages ?>
<?php $form->setAttribute('action', ''); ?>
<?php $form->setAttribute('class', 'form-horizontal'); ?>
<?php $form->setAttribute('enctype', 'multipart/form-data'); ?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formRow($form->get('rate_box')); ?>
<?php echo $this->formInput($form->get('submit')->setAttributes(array('value' => 'Vote', 'class' => 'btn btn-primary'))); ?>       
<?php echo $this->form()->closeTag(); ?>
</body>
</html>