<?php $this->headTitle('Edit Profile', 'PREPEND'); ?>
<div class="account-container btm10">
    <div class="form-content clearfix">
        <h1><i class="iconbig-pencil"></i>&nbsp;<?php echo $this->translate('Update Profile'); ?></h1>
        
        <?php $messages = $form->getMessages(); ?>
        <?php $form->setAttribute('action', $this->url('user', array('action' => 'edit', 'id' => $user_id))); ?>
        <?php $form->setAttribute('class', 'form-horizontal'); ?>
        <?php echo $this->form()->openTag($form); ?>
        
        <div class="login-fields">
            <div class="field">
                <?php echo $this->formLabel($form->get('display_name')); ?>
                <?php echo $this->formInput($form->get('display_name')->setAttributes(array('placeholder' => 'Display Name', 'class' => 'login username-field'))); ?>
                <?php if (isset($messages['display_name'])) {
                    echo '<br />'.$this->alertBlock(implode('<br />', $messages['display_name']), 'alert-danger');
                } ?>
            </div>
            
            <p><?php echo $this->translate('Optionally, you can modify your existing password by filling the fields below:'); ?></p>
            
            <div class="field">
                <?php echo $this->formLabel($form->get('password')); ?>
                <?php echo $this->formInput($form->get('password')->setAttributes(array('placeholder' => 'Password', 'class' => 'login password-field'))); ?>
                <?php if (isset($messages['password'])) {
                    echo '<br />'.$this->alertBlock(implode('<br />', $messages['password']), 'alert-danger');
                } ?>
            </div>
            <div class="field">
                <?php echo $this->formLabel($form->get('passwordconfirmation')); ?>
                <?php echo $this->formInput($form->get('passwordconfirmation')->setAttributes(array('placeholder' => 'Password Confirmation', 'class' => 'login password-field'))); ?>
                <?php if (isset($messages['passwordconfirmation'])) {
                    echo '<br />'.$this->alertBlock(implode('<br />', $messages['passwordconfirmation']), 'alert-danger');
                } ?>
            </div>
        </div>
        <div class="login-actions">
        <?php echo $this->formInput($form->get('submit')->setAttributes(array('value' => 'Save', 'class' => 'btn btn-primary pull-right btn-signin'))); ?>       
        </div>
        
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>