<?php $this->headTitle('Edit Profile', 'PREPEND'); ?>
<div class="account-container btm10">
    <div class="form-content clearfix">
        <h1><i class="iconbig-pencil"></i>&nbsp;<?php echo $this->translate('Update Profile'); ?></h1>
        
        <?php $messages = $form->getMessages(); ?>
        <?php $form->setAttribute('action', $this->url('user', array('action' => 'edit', 'id' => $user_id))); ?>
        <?php $form->setAttribute('class', 'form-horizontal'); ?>
        <?php echo $this->form()->openTag($form); ?>
        
        <div class="login-fields">
            <?php 
                echo $this->partial('partial/field.phtml', array(
                    'form' => $form,
                    'field' => 'display_name',
                    'inputAttributes' => array('placeholder' => 'Display Name', 'class' => 'login username-field')
                )); 
            ?>
            <p><?php echo $this->translate('Optionally, you can modify your existing password by filling the fields below:'); ?></p>
            
            <?php 
                echo $this->partial('partial/field.phtml', array(
                    'form' => $form,
                    'field' => 'password',
                    'inputAttributes' => array('placeholder' => 'Password', 'class' => 'login password-field')
                )); 
            ?>
            
            <?php 
                echo $this->partial('partial/field.phtml', array(
                    'form' => $form,
                    'field' => 'passwordconfirmation',
                    'inputAttributes' => array('placeholder' => 'Password Confirmation', 'class' => 'login password-field')
                )); 
            ?>
        </div>
        <div class="login-actions">
        <?php echo $this->formInput($form->get('submit')->setAttributes(array('value' => 'Save', 'class' => 'btn btn-primary pull-right btn-signin'))); ?>       
        </div>
        
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>