<?php $this->headTitle('Log in', 'PREPEND') ; ?>
<?php
// Prepare the flash messenger
use \Zend\Mvc\Controller\Plugin\FlashMessenger as PluginFlashMessenger;
$this->flashMessenger()->setMessageOpenFormat("<div%s><button type='button' class='close' data-dismiss='alert'>&times;</button>");
$this->flashMessenger()->setMessageSeparatorString('');
$this->flashMessenger()->setMessageCloseString('</div>');
?>
<div class="account-container btm10">
    <div class="form-content clearfix">
        <h1><i class="iconbig-lock"></i>&nbsp;<?php echo $this->translate('Log in'); ?></h1>
        
        <?php echo $this->flashMessenger()->render(PluginFlashMessenger::NAMESPACE_SUCCESS, array('alert', 'alert-success')); ?>
        <?php $messages = $this->flashMessenger()->getCurrentErrorMessages();?>
        <?php if (!empty($messages)) { 
            echo $this->alertBlock(implode('<br />', $messages), 'alert-danger'); 
        } ?>
        <?php
        // Remember to clear messages after displaying them
        use Zend\Mvc\Controller\Plugin\FlashMessenger;
        $this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_ERROR);
        ?>
        
        <?php $messages = $form->getMessages(); // Error messages ?>
        <?php //$form->setAttribute('action', $this->url('login')); ?>
        <?php $form->setAttribute('class', 'form-horizontal'); ?>
        <?php echo $this->form()->openTag($form); ?>
        
        <p><?php echo $this->translate("Login using your registered account: "); ?></p>
        <div class="login-fields">
            <?php 
                echo $this->partial('partial/field.phtml', array(
                    'form' => $form,
                    'field' => 'email',
                    'inputAttributes' => array('placeholder' => 'Email', 'class' => 'login username-field')
                )); 
            ?>
            
            <?php 
                echo $this->partial('partial/field.phtml', array(
                    'form' => $form,
                    'field' => 'password',
                    'inputAttributes' => array('placeholder' => 'Password', 'class' => 'login password-field')
                )); 
            ?>
        </div>
        <div class="login-actions">
        <?php echo $this->formInput($form->get('submit')->setAttributes(array('value' => 'Log in', 'class' => 'btn btn-primary pull-right btn-signin'))); ?>       
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
