<?php $this->headTitle('Log in', 'PREPEND') ; ?>
<h1 class="text-center"><?php echo $this->translate('Old Stuff Trade System'); ?></h1>
<?php
// Prepare the flash messenger
use \Zend\Mvc\Controller\Plugin\FlashMessenger as PluginFlashMessenger;
?>
<div class="row">
    <?php $messages = $this->flashMessenger()->getCurrentErrorMessages();?>
    <?php if (!empty($messages)) { ?>
    <div class="alert alert-danger"><?php echo implode('<br />', $messages); ?></div>
    <?php } ?>
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title text-center"><span class="glyphicon glyphicon-log-in"></span>&nbsp;<?php echo $this->translate('Log in'); ?></h3>
            </div>
            <div class="panel-body">
                <?php $messages = $form->getMessages(); // Error messages ?>
                <?php $form->setAttribute('action', $this->url('login')); ?>
                <?php $form->setAttribute('class', 'form-horizontal'); ?>
                <?php echo $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('email')); ?>
                    <div class="col-lg-8">
                        <?php echo $this->formInput($form->get('email')); ?>
                        <?php if (isset($messages['email'])) { ?>
                        <br /><div class="alert alert-danger"><?php echo implode('<br />', $messages['email']); ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('password')); ?>
                    <div class="col-lg-8">
                        <?php echo $this->formInput($form->get('password')); ?>
                        <?php if (isset($messages['password'])) { ?>
                        <br /><div class="alert alert-danger"><?php echo implode('<br />', $messages['password']); ?></div>
                        <?php } ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-8 col-lg-offset-4">
                        <?php echo $this->formInput($form->get('submit')->setAttribute('value', 'Log in')); ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
