<?php $this->headTitle('Log in', 'PREPEND') ; ?>
<?php
// Prepare the flash messenger
use \Zend\Mvc\Controller\Plugin\FlashMessenger as PluginFlashMessenger;
$this->flashMessenger()->setMessageOpenFormat("<div%s><button type='button' class='close' data-dismiss='alert'>&times;</button>");
$this->flashMessenger()->setMessageSeparatorString('');
$this->flashMessenger()->setMessageCloseString('</div>');
?>
<div class="account-container btm10">
    <div class="form-content clearfix">
        <h1><i class="iconbig-lock"></i>&nbsp;<?php echo $this->translate('Log in'); ?></h1>
        
        <?php echo $this->flashMessenger()->render(PluginFlashMessenger::NAMESPACE_SUCCESS, array('alert', 'alert-success')); ?>
        <?php $messages = $this->flashMessenger()->getCurrentErrorMessages();?>
        <?php if (!empty($messages)) { 
            echo $this->alertBlock(implode('<br />', $messages), 'alert-danger'); 
        } ?>
        <?php
        // Remember to clear messages after displaying them
        use Zend\Mvc\Controller\Plugin\FlashMessenger;
        $this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_ERROR);
        ?>
        
        <?php $messages = $form->getMessages(); // Error messages ?>
        <?php $form->setAttribute('action', $this->url('login')); ?>
        <?php $form->setAttribute('class', 'form-horizontal'); ?>
        <?php echo $this->form()->openTag($form); ?>
        
        <p><?php echo $this->translate("Login using your registered account: "); ?></p>
        <div class="login-fields">
            <div class="field">
                <?php echo $this->formLabel($form->get('email')); ?>
                <?php echo $this->formInput($form->get('email')->setAttributes(array('placeholder' => 'Email', 'class' => 'login username-field'))); ?>
                <?php if (isset($messages['email'])) {
                    echo '<br />'.$this->alertBlock(implode('<br />', $messages['email']), 'alert-danger');
                } ?>
            </div>
            <div class="field">
                <?php echo $this->formLabel($form->get('password')); ?>
                <?php echo $this->formInput($form->get('password')->setAttributes(array('placeholder' => 'Password', 'class' => 'login password-field'))); ?>
                <?php if (isset($messages['password'])) {
                    echo '<br />'.$this->alertBlock(implode('<br />', $messages['password']), 'alert-danger');
                } ?>
            </div>
        </div>
        <div class="login-actions">
        <?php echo $this->formInput($form->get('submit')->setAttributes(array('value' => 'Log in', 'class' => 'btn btn-primary pull-right btn-signin'))); ?>       
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
