<?php $this->headTitle($this->translate('Profile'), 'PREPEND'); ?>
<h1 class="text-center btm5"><?php echo $this->translate('Your Profile'); ?></h1>
<?php
// Prepare the flash messenger
use \Zend\Mvc\Controller\Plugin\FlashMessenger as PluginFlashMessenger;
$this->flashMessenger()->setMessageOpenFormat("<div%s><button type='button' class='close' data-dismiss='alert'>&times;</button>");
$this->flashMessenger()->setMessageSeparatorString('');
$this->flashMessenger()->setMessageCloseString('</div>');
?>
<div class="row">
    <div class="span8 offset2 gallery content-block">
        <?php echo $this->flashMessenger()->render(PluginFlashMessenger::NAMESPACE_SUCCESS, array('alert', 'alert-success')); ?>
        <div class="row">
            <div class="span2">
                <img class="img-polaroid" src="http://www.gravatar.com/avatar/<?php echo md5(trim($user->email)); ?>?s=200" />
            </div>
            <div class="span6">
                <blockquote><h1><?php echo $user->display_name; ?></h1></blockquote>
                <span class="glyphicon glyphicon-envelope"></span>&nbsp;<?php echo $user->email; ?>
                <br /><br />
                <a href="<?php echo $this->url('user', array('action' => 'edit', 'id' => $user->user_id));?>" class="btn btn-primary">
                <?php echo $this->translate('Edit Profile'); ?>
                </a>
            </div>
        </div>
    </div>
</div>