<?php $this->headTitle($this->translate('Profile'), 'PREPEND'); ?>
<h1 class="text-center"><?php echo $this->translate('Your Profile'); ?></h1>
<div class="row">
    <div class="col-md-2 col-md-offset-2">
        <img class="img-thumbnail" src="http://www.gravatar.com/avatar/<?php echo md5(trim($user->email)); ?>?s=200" />
    </div>
    <div class="col-md-6">
        <blockquote><?php echo $user->display_name; ?></blockquote>
        <span class="glyphicon glyphicon-envelope"></span>&nbsp;<?php echo $user->email; ?>
    </div>
</div>