<?php $this->headTitle($this->translate('Register'), 'PREPEND'); ?>
<h1 class="text-center"><?php echo $this->translate('Old Stuff Trade System'); ?></h1>
<div class="row">
    <?php $messages = $this->flashMessenger()->getCurrentSuccessMessages();?>
    <?php if (!empty($messages)) { ?>
    <div class="alert alert-success"><?php echo implode('<br />', $messages); ?></div>
    <?php } ?>
    <?php $messages = $this->flashMessenger()->getCurrentErrorMessages();?>
    <?php if (!empty($messages)) { ?>
    <div class="alert alert-danger"><?php echo implode('<br />', $messages); ?></div>
    <?php } ?>
    <?php
    // Remember to clear messages after displaying them
    use Zend\Mvc\Controller\Plugin\FlashMessenger;
    $this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_ERROR);
    $this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_SUCCESS);
    ?>
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title text-center"><?php echo $this->translate('Register'); ?></h3>
            </div>
            <div class="panel-body">
                <?php $messages = $form->getMessages(); // Error messages ?>
                <?php $form->setAttribute('action', $this->url('register')); ?>
                <?php $form->setAttribute('class', 'form-horizontal'); ?>
                <?php echo $this->form()->openTag($form); ?>
                
                <?php echo $this->formField($form, 'email'); ?>
                <?php echo $this->formField($form, 'password'); ?>
                <?php echo $this->formField($form, 'passwordconfirmation'); ?>
                
                <div class="form-group">
                    <div class="col-lg-8 col-lg-offset-4">
                        <?php echo $this->formInput($form->get('submit')); ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
