<?php $this->headTitle($this->translate('Register'), 'PREPEND'); ?>
<div class="account-container btm10">
    <div class="form-content clearfix">
        <h1><i class="iconbig-note-write"></i>&nbsp;<?php echo $this->translate('Register'); ?></h1>
        
        <?php $messages = $this->flashMessenger()->getCurrentSuccessMessages();?>
        <?php if (!empty($messages)) { 
            echo $this->alertBlock(implode('<br />', $messages), 'alert-success'); 
        } ?>
        <?php $messages = $this->flashMessenger()->getCurrentErrorMessages();?>
        <?php if (!empty($messages)) { 
            echo $this->alertBlock(implode('<br />', $messages), 'alert-danger'); 
        } ?>
        <?php
        // Remember to clear messages after displaying them
        use Zend\Mvc\Controller\Plugin\FlashMessenger;
        $this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_ERROR);
        $this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_SUCCESS);
        ?>
        
        <?php $messages = $form->getMessages(); // Error messages ?>
        <?php $form->setAttribute('action', $this->url('register')); ?>
        <?php $form->setAttribute('class', 'form-horizontal'); ?>
        <?php echo $this->form()->openTag($form); ?>
        
        <p><?php echo $this->translate('Sign up manually: '); ?></p>
        
        <div class="login-fields">
            <?php 
                echo $this->partial('partial/field.phtml', array(
                    'form' => $form,
                    'field' => 'email',
                    'inputAttributes' => array('placeholder' => 'Email', 'class' => 'login username-field')
                )); 
            ?>
            
            <?php 
                echo $this->partial('partial/field.phtml', array(
                    'form' => $form,
                    'field' => 'password',
                    'inputAttributes' => array('placeholder' => 'Password', 'class' => 'login password-field')
                )); 
            ?>
            
            <?php 
                echo $this->partial('partial/field.phtml', array(
                    'form' => $form,
                    'field' => 'passwordconfirmation',
                    'inputAttributes' => array('placeholder' => 'Password Confirmation', 'class' => 'login password-field')
                )); 
            ?>
        </div>
        <div class="login-actions">
        <?php echo $this->formInput($form->get('submit')->setAttributes(array('value' => 'Submit', 'class' => 'btn btn-primary pull-right btn-signin'))); ?>       
        </div>
        <?php echo $this->form()->closeTag(); ?>
            
    </div>
</div>
