<?php $this->headTitle($this->translate('Add Stuff'), 'PREPEND'); ?>
<div class="account-container btm10">
    <div class="form-content clearfix">
        <h1><i class="iconbig-note-write"></i>&nbsp;<?php echo $this->translate('Add New Stuff'); ?></h1>
        
        <?php $messages = $this->flashMessenger()->getCurrentSuccessMessages();?>
        <?php if (!empty($messages)) { 
            echo $this->alertBlock(implode('<br />', $messages), 'alert-success'); 
        } ?>
        <?php $messages = $this->flashMessenger()->getCurrentErrorMessages();?>
        <?php if (!empty($messages)) { 
            echo $this->alertBlock(implode('<br />', $messages), 'alert-danger'); 
        } ?>
        <?php
        // Remember to clear messages after displaying them
        use Zend\Mvc\Controller\Plugin\FlashMessenger;
        $this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_ERROR);
        $this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_SUCCESS);
        ?>
        <?php $messages = $form->getMessages(); // Error messages ?>
        <?php $form->setAttribute('action', ''); ?>
        <?php $form->setAttribute('class', 'form-horizontal'); ?>
        <?php $form->setAttribute('enctype', 'multipart/form-data'); ?>
        <?php echo $this->form()->openTag($form); ?>
        
        <div class="login-fields">
            <?php 
                echo $this->partial('partial/field.phtml', array(
                    'form' => $form,
                    'field' => 'stuffname',
                    'inputAttributes' => array('placeholder' => 'Name', 'class' => 'login username-field')
                )); 
            ?>
            <?php echo $this->formTextArea($form->get('description')->setAttributes(array('placeholder' => 'Description', 'class' => ''))); ?>
            <br /><br />
            <?php echo $this->formSelect($form->get('category'));?>
            
            <?php echo $this->formFile($form->get('image')); ?>
             <br /><br />      
            <?php //echo $this->formRadio($form->get('purpose'));?>
            <br /><br />
            <?php 
                echo $this->partial('partial/field.phtml', array(
                    'form' => $form,
                    'field' => 'price',
                    'inputAttributes' => array('placeholder' => 'Price', 'class' => 'login password-field')
                )); 
            ?>
            <?php 
                echo $this->partial('partial/field.phtml', array(
                    'form' => $form,
                    'field' => 'desiredstuff',
                    'inputAttributes' => array('placeholder' => 'Desired Stuff', 'class' => 'login password-field')
                ));
                 
            ?>
        </div>
        <div class="login-actions">
        <?php echo $this->formInput($form->get('submit')->setAttributes(array('value' => 'Add', 'class' => 'btn btn-primary pull-right btn-signin'))); ?>
        </div>

        <?php echo $this->form()->closeTag(); ?>
            
    </div>
</div>