<?php $this->headTitle($this->translate('Add Stuff'), 'PREPEND'); ?>
<div class="gallery content-block span6 offset3">
<h1 class="text-center"><i class="iconbig-note-write"></i>&nbsp;<?php echo $this->translate('Add New Stuff'); ?></h1>

<?php $messages = $this->flashMessenger()->getCurrentSuccessMessages();?>
<?php if (!empty($messages)) { 
    echo $this->alertBlock(implode('<br />', $messages), 'alert-success'); 
} ?>
<?php $messages = $this->flashMessenger()->getCurrentErrorMessages();?>
<?php if (!empty($messages)) { 
    echo $this->alertBlock(implode('<br />', $messages), 'alert-danger'); 
} ?>
<?php
// Remember to clear messages after displaying them
use Zend\Mvc\Controller\Plugin\FlashMessenger;
$this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_ERROR);
$this->flashMessenger()->clearCurrentMessagesFromNamespace(FlashMessenger::NAMESPACE_SUCCESS);
?>
<?php $messages = $form->getMessages(); // Error messages ?>
<?php 
    $form->setAttribute('action', '');
    $form->setAttribute('class', 'form-horizontal');
    $form->setAttribute('enctype', 'multipart/form-data');
    
    echo $this->form()->openTag($form);
    echo $this->partial('partial/field.phtml', 
        array(
            'form' => $form, 
            'field' => 'stuffname', 
            'inputViewHelper' => 'formInput')
    );
    echo $this->partial('partial/field.phtml', 
        array(
            'form' => $form, 
            'field' => 'description', 
            'inputViewHelper' => 'formTextArea')
    );
    echo $this->partial('partial/field.phtml', 
        array(
            'form' => $form, 
            'field' => 'category',
            'inputViewHelper' => 'formSelect')
    );
    echo $this->partial('partial/field.phtml', 
        array(
            'form' => $form, 
            'field' => 'image', 
            'inputViewHelper' => 'formFile')
    );
    echo $this->partial('partial/field.phtml', 
        array(
            'form' => $form, 
            'field' => 'purpose', 
            'inputViewHelper' => 'formRadio')
    );
    echo $this->formInput($form->get('submit')->setAttributes(array('value' => 'Add', 'class' => 'btn btn-primary pull-right')));
    echo $this->form()->closeTag(); 
?>
</div>