<?php $this->headTitle($this->translate('Edit Stuff'), 'PREPEND'); ?>
<div class="gallery span3 offset1 content-block">
    <?php echo $this->partial('stuff/partial/user-profile.phtml', array('user' => $this->identity())); ?>
</div>
<div class="gallery content-block span7">
<h1 class="text-center"><i class="iconbig-note-write"></i>&nbsp;<?php echo $this->translate('Edit Stuff'); ?></h1>

<?php echo $this->partial('partial/current-flash-messages.phtml'); ?>

<?php 
    $form->setAttribute('action', '');
    $form->setAttribute('class', 'form-horizontal');
    $form->setAttribute('enctype', 'multipart/form-data');
    
    echo $this->form()->openTag($form);
    echo $this->partial('partial/stuff-field.phtml', 
        array(
            'form' => $form, 
            'field' => 'stuffname', 
            'inputViewHelper' => 'formInput')
    );
    echo $this->partial('partial/stuff-field.phtml', 
        array(
            'form' => $form, 
            'field' => 'description', 
            'inputViewHelper' => 'formTextArea')
    );
    echo $this->partial('partial/stuff-field.phtml', 
        array(
            'form' => $form, 
            'field' => 'category',
            'inputViewHelper' => 'formSelect')
    );
    echo $this->partial('partial/stuff-field.phtml', 
        array(
            'form' => $form, 
            'field' => 'image', 
            'inputViewHelper' => 'formFile')
    );
    echo $this->partial('partial/stuff-field.phtml', 
        array(
            'form' => $form, 
            'field' => 'purpose', 
            'inputViewHelper' => 'formRadio')
    );
    echo $this->partial('partial/stuff-field.phtml', 
        array(
            'form' => $form, 
            'field' => 'price', 
            'inputViewHelper' => 'formInput')
    );
    echo $this->partial('partial/stuff-field.phtml', 
        array(
            'form' => $form, 
            'field' => 'desiredstuff', 
            'inputViewHelper' => 'formInput')
    );
    echo $this->formInput($form->get('submit')->setAttributes(array('value' => 'Save', 'class' => 'btn btn-primary pull-right')));
    echo $this->form()->closeTag(); 
?>
</div>