<?php $this->headTitle($this->translate('Edit Stuff'), 'PREPEND'); ?>
<div class="notification">
    <?php foreach ($success_messages as $message) { ?>
    <div class="alert alert-success"><?php echo $message; ?></div>
    <?php } ?>
    <?php foreach ($error_messages as $message) { ?>
    <div class="alert alert-danger"><?php echo $message; ?></div>
    <?php } ?>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title text-center"><?php echo $this->translate('Edit Stuff'); ?></h3>
            </div>
            <div class="panel-body">
                <?php $form->setAttribute('action', ''); ?>
                <?php $form->setAttribute('class', 'form-horizontal'); ?>
                <?php echo $this->form()->openTag($form); ?>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('stuffname')); ?>
                    <div class="col-lg-8">
                        <?php echo $this->formText($form->get('stuffname')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('description')); ?>
                    <div class="col-lg-8">
                        <?php echo $this->formTextArea($form->get('description')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('price')); ?>
                    <div class="col-lg-8">
                        <?php echo $this->formText($form->get('price')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-8 col-lg-offset-4">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
