<?php 
    $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-select.css');
    $this->headScript()->prependFile($this->basePath() . '/js/bootstrap-select.min.js')
                       ->prependScript('jQuery(document).ready(function(){jQuery(".selectpicker").selectpicker()})');
    $session = new Zend\Session\Container('stuff');
    $filter_category = $session->offsetGet('filter.category');
    $filter_purpose = $session->offsetGet('filter.purpose');
?>
<div class="row">
    <div class="filter-bar span12">
        <form id="filter-form" method="POST">
            <select class="selectpicker" id="category-select">
                <option value=""><?php echo $this->translate('All Category'); ?></option>
                 <?php foreach ($categories as $category) { ?>
                <option value="<?php echo $category->cat_id; ?>"<?php echo ($category->cat_id == $filter_category) ? ' selected="selected"' : ''; ?>><?php echo $category->cat_name; ?></option>
                <?php } ?>
            </select>
            <input type="hidden" id="filter-category" name="filter_category" value="<?php echo (int) $filter_category; ?>" />
            <div class="btn-group" id="purpose-select" data-toggle="buttons-radio">
                <button type="button" class="btn<?php echo empty($filter_purpose) ? ' active' : ''; ?>" data-value=""><?php echo $this->translate('Any Purpose'); ?></button>
                <button type="button" class="btn<?php echo ($filter_purpose == 'sell') ? ' active' : ''; ?>" data-value="sell"><?php echo $this->translate('For Sale'); ?></button>
                <button type="button" class="btn<?php echo ($filter_purpose == 'trade') ? ' active' : ''; ?>" data-value="trade"><?php echo $this->translate('For Trade'); ?></button>
            </div>
            <input type="hidden" id="filter-purpose" name="filter_purpose" value="<?php echo (string) $filter_purpose; ?>" />
        </form>
    </div>
</div>
<div class="row" id="gallery-container">
    <div class="span3 item gallery">
        <div class="nav-headers">
            <blockquote><h4><?php echo $this->translate('Find some interesting stuffs with amazing prices or submit your own things. You will never know what you can find here!'); ?></h4></blockquote>
            <div class="clearfix"></div>
        </div>
    </div>
    <?php if ($paginator->getTotalItemCount()) { ?>
    <?php 
        $this->partialLoop()->setObjectKey('object');
        echo $this->partialLoop('partial/stuff.phtml', $paginator->getCurrentItems()); ?>
    <?php } else { ?>
    <div class="span9 item gallery text-center">
        <h2 class="muted"><?php echo $this->translate('No items here'); ?></h2>
        <h5><?php echo $this->translate('You can change your search criteria to get more items!'); ?></h5>
    </div>
    <?php } ?>
</div>
<?php $this->partial()->setObjectKey('object'); echo $this->partial('partial/pagination.phtml', $paginator); ?>