<div class="row" id="gallery-container">
    <div class="span3 item">
        <div class="nav-headers">
            <h4>Find some interesting stuffs or submit your own things. You will never know what you can find here!</h4>
        </div>
        <ul class="nav nav-tabs nav-stacked">
            <li class="active"><a href="#">All</a></li>
            <?php foreach ($categories as $category) { ?>
            <li><a href="#"><?php echo $category->cat_name; ?></a></li>
            <?php } ?>
        </ul>
    </div>
    
    <?php 
        $this->partialLoop()->setObjectKey('object');
        echo $this->partialLoop('partial/stuff.phtml', $paginator->getCurrentItems()); ?>
</div>
<?php $this->partial()->setObjectKey('object'); echo $this->partial('partial/pagination.phtml', $paginator); ?>