<?php $this->headTitle($this->translate('Inventory'), 'PREPEND'); 
use \Zend\Mvc\Controller\Plugin\FlashMessenger as PluginFlashMessenger;
?>

<div class="row" id="gallery-container" style="margin: 0 auto">
    <div class="row">
    <div class="span8 offset2 gallery content-block">
        <?php echo $this->flashMessenger()->render(PluginFlashMessenger::NAMESPACE_SUCCESS, array('alert', 'alert-success')); ?>
        <div class="row">
            <div class="span2">
                <img class="img-polaroid" src="http://www.gravatar.com/avatar/<?php echo md5(trim($user->email)); ?>?s=200" />
            </div>
            <div class="span6">
                <blockquote><h1><?php echo $user->display_name; ?></h1></blockquote>
                <span class="glyphicon glyphicon-envelope"></span>&nbsp;<?php echo $user->email; ?>
                <br /><br />
                <a href="<?php echo $this->url('stuff', array('action' => 'add', 'user_id' => $user->user_id));?>" class="btn btn-primary">
                <?php echo $this->translate('Add stuff'); ?>
                </a>
            </div>
        </div>
    </div>
</div>
 </div> 

<div style="clear:both;margin:0 auto;text-align:center">    
    <a id="inventory" href="<?php echo $this->url('stuff', array( 'action' => 'index', 
                                                    'tab' => 'inventory',
                                                    'user_id' => $user->user_id));?>?tab=inventory" class="btn btn-primary" style="width:70px;margin: 0 -3px 0 -3px;">
            <?php echo $this->translate('Inventory'); ?>
    </a>   
    <a id="done" href="<?php echo $this->url('stuff', array( 'action' => 'index', 
                                                    'tab' => 'done',
                                                    'user_id' => $user->user_id));?>?tab=done" class="btn btn-primary" style="width:70px;margin: 0 -3px 0 -3px;">
            <?php echo $this->translate('Sold/Traded'); ?>
    </a>
    <a id="request" href="<?php echo $this->url('stuff', array( 'action' => 'index', 
                                                    'tab' => 'request',
                                                    'user_id' => $user->user_id));?>?tab=request" class="btn btn-primary" style="width:70px;margin: 0 -3px 0 -3px;">
            <?php echo $this->translate('Request'); ?>
    </a>   
    
</div>
<div class="row" style="margin: 0 auto;">
    <hr class="alt"/>
    <?php 
        $this->partialLoop()->setObjectKey('object');
        echo $this->partialLoop('partial/indexstuff.phtml', $paginator->getCurrentItems()); ?>
       <div style="clear:both"></div>

<?php $this->partial()->setObjectKey('object'); echo $this->partial('partial/pagination.phtml', $paginator); ?>
        
</div>

<script type="text/javascript" language="javascript">
    if ((document.URL).indexOf("inventory") !== -1) $("#inventory").addClass("active");
    if ((document.URL).indexOf("done") !== -1) $("#done").addClass("active");
    if ((document.URL).indexOf("request") !== -1) $("#request").addClass("active");
</script>