<?php $this->headTitle($stuff->stuff_name, 'PREPEND'); 
    $stuff = $this->stuff;
    $authorized = ($stuff->user == $this->identity());
    if ($authorized) {
        $this->deleteConfirmationScript();
    }
?>
<div class="row">
<div class="gallery span3 offset1 content-block">
    <?php echo $this->partial('stuff/partial/user-profile.phtml', array('user' => $stuff->user)); ?>
</div>
<div class="gallery content-block span7">
<h1 class="text-center"><?php echo $stuff->stuff_name; ?></h1>
    <div class="row-fluid stuff-item">
        <div class="span3 stuff-image">
            <?php if ($stuff->image !== "") { ?>
            <a class="group" rel="group1" href="<?php echo $this->basePath() . '/' . $stuff->image[0]; ?>">
                <img src="<?php echo $this->basePath() . '/' . $stuff->image[0]; ?>">
            </a>
            <?php } else { ?>
            <img src="holder.js/225x210/gray/text:[<?php echo $this->translate("Old Stuff Trade System"); ?>]">
            <?php } ?>
        </div>
        <div class="span9 stuff-info">
            <?php echo $this->partial('partial/flash-messages.phtml'); ?>
            <div class="stuff-value">
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <th><?php echo $this->translate('Owner'); ?></th>
                            <td><?php echo $stuff->user->display_name; ?></td>
                        </tr>
                        <tr>
                            <th><?php echo $this->translate('Description'); ?></th>
                            <td><?php echo $stuff->description; ?></td>
                        </tr>
                        <tr>
                            <th><?php echo $this->translate('Purpose'); ?></th>
                            <td><?php echo strtoupper($stuff->purpose); ?></td>
                        </tr>
                        <?php if (strpos($stuff->purpose, 'sell') !== false) { ?>
                        <tr>
                            <th><?php echo $this->translate('Price'); ?></th>
                            <td><?php echo $stuff->price; ?></td>
                        </tr>
                        <?php } ?>
                        <?php if (strpos($stuff->purpose, 'trade') !== false) { ?>
                        <tr>
                            <th><?php echo $this->translate('Desired Stuff'); ?></th>
                            <td><?php echo $stuff->desired_stuff; ?></td>
                        </tr>
                        <?php } ?>
                        <tr>
                            <th><?php echo $this->translate('State'); ?></th>
                            <td><?php echo $this->partial('stuff/partial/state-badge.phtml', array('state' => $stuff->state)); ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
       </div>
    </div>
    <?php if($authorized && $stuff->state <= 1) {?>
    <a href="<?php echo $this->stuffEditLink($stuff->stuff_id);?>" 
        class="btn btn-primary">
        <?php echo $this->translate('Edit'); ?>
    </a>
    <a href="<?php echo $this->stuffDeleteLink($stuff->stuff_id);?>" 
        class="btn btn-link delete-link">
        <?php echo $this->translate('Delete'); ?>
    </a>    
    <?php } else if (!$authorized && $stuff->state == 1) { ?>
    <?php if (strpos($stuff->purpose, 'sell') !== false) { ?>
    <a href="<?php echo $this->stuffBuyLink($stuff->stuff_id); ?>" class="btn btn-success"><i class="icon-shopping-cart"></i>&nbsp;<?php echo $this->translate("Buy"); ?></a>
    <?php } ?>
    <?php if (strpos($stuff->purpose, 'trade') !== false) { ?>
    <a href="<?php echo $this->stuffTradeLink($stuff->stuff_id); ?>" class="btn btn-info"><i class="icon-random"></i>&nbsp;<?php echo $this->translate("Trade"); ?></a>
    <?php } ?>
    <?php } ?>
</div>
</div>
<?php if ($authorized) { ?>
<hr class="alt"/>
<div class="row">
    <div class="gallery span8 offset2 user-stuff-list">
        <?php if (count($this->requests) > 0) { ?>
        <?php 
            $this->partialLoop()->setObjectKey('object');
            echo $this->partialLoop('partial/request.phtml', $this->requests); ?>
        <?php } else { ?>
        <div class="text-center">
            <h2 class="muted"><?php echo $this->translate('No request for this item'); ?></h2>            
        </div>
        <?php } ?>
    </div>
</div>
<?php if ($stuff->state > 1 && isset($this->acceptedRequest)) { ?>
<?php $requestor = $this->acceptedRequest->requestor; ?>
<div class="row">
    <div class="gallery span8 offset2 content-block"> 
        <h2 class="text-center"><?php echo $this->translate('Requestor Contact'); ?></h1>
        <table class="table">
            <tr>
                <th><?php echo $this->translate('Name'); ?></th>
                <td><?php echo $requestor->display_name; ?></td>
            </tr>
            <tr>
                <th><?php echo $this->translate('Email'); ?></th>
                <td><?php echo $requestor->email; ?></td>
            </tr>
             <tr>
                <th><?php echo $this->translate('Phone'); ?></th>
                <td><?php echo $requestor->contact->phone; ?></td>
            </tr>
            <tr>
                <th><?php echo $this->translate('Address'); ?></th>
                <td><?php echo $requestor->contact->address; ?></td>
            </tr>
            <tr>
                <th><?php echo $this->translate('City'); ?></th>
                <td><?php echo $requestor->contact->city; ?></td>
            </tr>
            <tr>
                <th><?php echo $this->translate('State'); ?></th>
                <td><?php echo $requestor->contact->state; ?></td>
            </tr>
            <tr>
                <th><?php echo $this->translate('Zipcode'); ?></th>
                <td><?php echo $requestor->contact->zipcode; ?></td>
            </tr>
            <tr>
                <th><?php echo $this->translate('Country'); ?></th>
                <td><?php echo $requestor->contact->country; ?></td>
            </tr>
        </table>        
    </div>
</div>
<?php } ?> 
<?php } ?>

