<?php $this->headTitle($this->translate('Your Requests'), 'PREPEND'); 

$authorized = ($this->identity() == $user);
if ($authorized) {
    $this->deleteConfirmationScript(); // Init confirmation popup upon stuff deletion
}
$session = new Zend\Session\Container('stuff\user\\'.$user->user_id);
$filter_tab = $session->offsetGet('filter.tab');
?>

<div class="row">
    <div class="span8 offset2 gallery content-block">
        <?php echo $this->partial('partial/flash-messages.phtml'); ?>
        <div class="row">
            <div class="span2">
                <img class="img-polaroid" src="http://www.gravatar.com/avatar/<?php echo md5(trim($user->email)); ?>?s=200" />
            </div>
            <div class="span5">
                <blockquote><h1><?php echo $user->display_name; ?></h1></blockquote>
                <span class="icon-envelope"></span>&nbsp;<?php echo $user->email; ?>
                <br /><br />
                <?php if ($authorized) { ?>
                <a href="<?php echo $this->url('user', array('action' => 'edit', 'id' => $user->user_id), array('query' => array('redirect' => $this->stuffUserLink($user->user_id)))); ?>" class="btn"><?php echo $this->translate('Edit Profile'); ?></a>
                <a href="<?php echo $this->stuffAddLink();?>" class="btn btn-primary">
                <?php echo $this->translate('Add stuff'); ?>
                </a>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
<hr class="alt"/>
<div class="row">
    <div class="gallery span8 offset2 user-stuff-list">
        <?php if (count($this->requests) > 0) { ?>
        <?php 
            $this->partialLoop()->setObjectKey('object');
            echo $this->partialLoop('partial/request.phtml', $this->requests); ?>
        <?php } else { ?>
        <div class="text-center">
            <h2 class="muted"><?php echo $this->translate('You have not sent any request'); ?></h2>            
        </div>
        <?php } ?>
    </div>
</div>
