<?php $this->headTitle($this->translate('Trade Request'), 'PREPEND');
    $user = $this->identity();
    $stuff = $this->stuff; 
?>
<div class="row">
<div class="gallery content-block span8 offset2">
    <h1 class="text-center"><i class="iconbig-note-write"></i>&nbsp;<?php echo $this->translate('Request Info'); ?></h1>
    <div>Please review the information below for your trade request:</div>
    <br />
    <div class="row-fluid stuff-item">
        <?php echo $this->partial('partial/current-flash-messages.phtml'); ?>
        
        <div class="span3 stuff-image">
            <?php if ($stuff->image !== "") { ?>
            <a class="group" rel="group1" href="<?php echo $this->basePath() . '/' . $stuff->image[0]; ?>">
                <img src="<?php echo $this->basePath() . '/' . $stuff->image[0]; ?>">
            </a>
            <?php } else { ?>
            <img src="holder.js/225x210/gray/text:[<?php echo $this->translate("Old Stuff Trade System"); ?>]">
            <?php } ?>
        </div>
        <div class="span9 stuff-info">
            <?php echo $this->form()->openTag($form); ?>
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th><?php echo $this->translate('Stuff Name'); ?></th>
                        <td><?php echo $stuff->stuff_name; ?></td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate('Desired Stuff'); ?></th>
                        <td><?php echo $stuff->desired_stuff; ?></td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate('Owner'); ?></th>
                        <td><?php echo $stuff->user->display_name; ?></td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate('Requestor'); ?></th>
                        <td><?php echo $user->display_name; ?></td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate('Proposed Stuff'); ?></th>
                        <td>
                        <?php 
                            echo $this->formSelect($form->get('proposed_stuff')); 
                            $messages = $form->getMessages();
                            if (isset($messages['proposed_stuff']))
                                echo $this->alertBlock(implode('<br />', $messages['proposed_stuff']));
                        ?>
                        </td>
                    </tr>
                </tbody>
            </table>
            <a href="<?php echo $this->stuffUserLink($this->identity()->user_id);?>" 
                class="btn">
                <?php echo $this->translate('Cancel'); ?>
            </a>
            <?php echo $this->formInput($form->get('submit')->setAttributes(array('value' => 'Send Request', 'class' => 'btn btn-primary pull-right'))); ?>
            <?php echo $this->form()->closeTag(); ?>            
        </div>
    </div>
</div>
</div>