    <link type="text/css" href="http://www.fyneworks.com/@/js/jquery/ui/jquery.ui.css" rel="stylesheet"/>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js" type="text/javascript"></script>
    <link href='documentation/documentation.css' type="text/css" rel="stylesheet"/>
    <script src='http://www.fyneworks.com/jquery/documentation/documentation.js' type="text/javascript"></script>
<?php $this->headTitle($this->translate('Your Stuff'), 'PREPEND'); 

$authorized = ($this->identity() == $user);
if ($authorized) {
    $this->deleteConfirmationScript(); // Init confirmation popup upon stuff deletion
}
$session = new Zend\Session\Container('stuff\user\\'.$user->user_id);
$filter_tab = $session->offsetGet('filter.tab');
?>

<div class="row">
    <div class="span8 offset2 gallery content-block">
        <?php echo $this->partial('partial/flash-messages.phtml'); ?>
        <div class="row">
            <div class="span2">
                <img class="img-polaroid" src="http://www.gravatar.com/avatar/<?php echo md5(trim($user->email)); ?>?s=200" />
            </div>
            <div class="span5">
                <blockquote><h1><?php echo $user->display_name; ?></h1></blockquote>
                <span class="icon-envelope"></span>&nbsp;<?php echo $user->email; ?>
                <br>
                <?php if ($this->identity())
                      { $logged_user = $this->identity(); ?>

                <a href="<?php echo $this->url('vote', array('action' => 'vote', 'user_id' => $logged_user->user_id, 'voted_user_id' => $user->user_id)); ?>" >Rate this user</a>
                <br>
                <?php } else { ?>
                    <p style="color:red; font-size:20px">You must log in to rate</p>
                <?php } ?>
                <?php 
                    if ($vote_result != null) {
                        echo "(Rating : " . round($vote_result->avgrate, 2) . " / " . $vote_result->numofvote . " votes)";
                        echo "<br>";
                        if ($vote_result->avgrate == 0)
                        { ?>
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                        <?php }
                        elseif ($vote_result->avgrate <= 0.5)
                        { ?>
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" checked="checked" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                        <?php }
                        elseif ($vote_result->avgrate <= 1)
                        { ?>
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" checked="checked" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                        <?php }
                        elseif ($vote_result->avgrate <= 1.5)
                        { ?>
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" checked="checked" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                        <?php }
                        elseif ($vote_result->avgrate <= 2)
                        { ?>
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" checked="checked" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                        <?php }
                        elseif ($vote_result->avgrate <= 2.5)
                        { ?>
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" checked="checked" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                        <?php }
                        elseif ($vote_result->avgrate <= 3)
                        { ?>
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" checked="checked" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                        <?php }
                        elseif ($vote_result->avgrate <= 3.5)
                        { ?>
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" checked="checked" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                        <?php }
                        elseif ($vote_result->avgrate <= 4)
                        { ?>
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" checked="checked" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                        <?php }
                        elseif ($vote_result->avgrate <= 4.5)
                        { ?>
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" checked="checked" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                        <?php }
                        else
                        { ?>
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" checked="checked" />
                        <?php }
                        } else { ?>
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                            <input name="star1" type="radio" class="star {split:2}" disabled="disabled" />
                        <?php } ?>
                
                <br /><br />
                <?php if ($authorized) { ?>
                <a href="<?php echo $this->url('user', array('action' => 'edit', 'id' => $user->user_id), array('query' => array('redirect' => $this->stuffUserLink($user->user_id)))); ?>" class="btn"><?php echo $this->translate('Edit Profile'); ?></a>
                <a href="<?php echo $this->stuffAddLink();?>" class="btn btn-primary">
                <?php echo $this->translate('Add stuff'); ?>
                </a>
                <?php } ?>
            </div>
        </div>
    </div>
</div>


<hr class="alt"/>
<div class="row">
    <?php if ($user == $this->identity()) { ?>
    <div class="tab-bar span8 offset2">
        <form class="filter-form" method="POST">
            <div id="tab-select" class="btn-group" data-toggle="buttons-radio">
                <button class="btn<?php echo ($filter_tab == 'inventory') ? ' active' : ''; ?>" type="button" data-value="inventory"><?php echo $this->translate("Inventory"); ?></button>
                <button class="btn<?php echo ($filter_tab == 'request') ? ' active' : ''; ?>" type="button" data-value="request"><?php echo $this->translate("On Request"); ?></button>
                <button class="btn<?php echo ($filter_tab == 'done') ? ' active' : ''; ?>" type="button" data-value="done"><?php echo $this->translate("Sold/Traded"); ?></button>
                <input type="hidden" id="filter-tab" name="filter_tab" value="<?php echo (string) $filter_tab; ?>" />
            </div>
        </form>
    </div>
    <?php } ?>
    <div class="span8 offset2 user-filter">
    <?php echo $this->partial('stuff/partial/filter-bar.phtml', array('namespace' => 'stuff\user\\'.$user->user_id, 'categories' => $categories)); ?>
    </div>
</div>
<div class="row">
    <div class="gallery span8 offset2 user-stuff-list">
        <?php if ($paginator->getTotalItemCount()) { ?>
        <?php 
            $this->partialLoop()->setObjectKey('object');
            echo $this->partialLoop('partial/stuff-item.phtml', $paginator->getCurrentItems()); ?>
        <?php } else { ?>
        <div class="text-center">
            <h2 class="muted"><?php echo $this->translate('No stuffs here'); ?></h2>
            <h5><?php echo $this->translate('Upload new one now or change the search criteria!'); ?></h5>
        </div>
        <?php } ?>
    </div>
</div>
<?php echo $this->partial('partial/pagination.phtml', array('paginator' => $paginator)); ?>  