<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Old Stuff Trade System'))->setSeparator(' - ')->setAutoEscape(false); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/jquery.fancybox.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery.isotope.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.css')
                        ->prependStylesheet($this->basePath() . '/css/icon-style.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/open-sans.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery.rating.css') ;?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.js')
            ->prependFile($this->basePath() . '/js/image-gallery.js')
            ->prependFile($this->basePath() . '/js/jquery.mousewheel-3.0.6.pack.js')
            ->prependFile($this->basePath() . '/js/jquery.fancybox.js')
            ->prependFile($this->basePath() . '/js/jquery.isotope.min.js')
            ->prependFile($this->basePath() . '/js/holder.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js')
            ->prependFile($this->basePath() . '/js/jquery.js')
            ->prependFile($this->basePath() . '/js/jquery.form.js')
            ->prependFile($this->basePath() . '/js/jquery.MetaData.js')
            ->prependFile($this->basePath() . '/js/jquery.rating.js')
            ->prependFile($this->basePath() . '/js/jquery.rating.pack.js')
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-fixed-top" role="navigation">
            <div class="navbar-inner">
                <div class="container-fluid">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="<?php echo $this->url('home') ?>"><img title="<?php echo $this->translate('Old Stuff Trade System') ?>" src="<?php echo $this->basePath() .'/img/os-logo.png'; ?>" alt="<?php echo $this->translate('Old Stuff Trade System') ?>" /></a>
                <div class="nav-collapse">
                    <?php echo $this->navigation()->menu()->renderPartial('navigation', 'partial/menu-left.phtml'); ?>
                    
                    <?php echo $this->navigation()->menu()->renderPartial('Stuff\Navigation\Head', 'partial/menu-right.phtml'); ?>
                </div><!--/.nav-collapse -->
                </div>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <div class="container footer">
            <hr class="alt">
            <footer>
                <p>Powered by Zend</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
