<?php $authorized = ($this->identity() == $this->object->user); ?>
<div class="row-fluid stuff-item">
    <div class="span3 stuff-image">
        <?php if ($this->object->image !== "") { ?>
        <a class="group" rel="group1" href="<?php echo $this->basePath() . '/' . $this->object->image[0]; ?>">
            <img src="<?php echo $this->basePath() . '/' . $this->object->image[0]; ?>">
        </a>
        <?php } else { ?>
        <img src="holder.js/225x210/gray/text:[<?php echo $this->translate("Old Stuff Trade System"); ?>]">
        <?php } ?>
    </div>
    <div class="span7 stuff-info">
        <h4>
            <?php echo $this->object->stuff_name; ?>
            <?php if ($this->object->state == 1) { ?>
            <label class="label label-success"><?php echo $this->translate('published'); ?></label>
            <?php } else if ($this->object->state == 0) { ?>
            <label class="label label-inverse"><?php echo $this->translate('unpublished'); ?></label>
            <?php } ?>
        </h4>
        <hr class="alt">
        <div class="stuff-description"><?php echo $this->object->description ?></div>
    </div>
    <div class="span2 stuff-buttons">
        <?php if ($authorized) { ?>
        <a href="<?php echo $this->url('stuff', array( 'action' => 'edit', 
                                                        'user_id' => $this->object->user->user_id, 
                                                        'stuff_id' => $this->object->stuff_id));?>" class="btn btn-primary" style="width:50px;">
            <?php echo $this->translate('Edit'); ?>
        </a>
        <a href="<?php echo $this->url('stuff', array( 'action' => 'delete', 
                                                        'user_id' => $this->object->user->user_id, 
                                                        'stuff_id' => $this->object->stuff_id));?>">
            <?php echo $this->translate('Delete'); ?>
        </a>
        <?php } else { ?>
        <a href="#" class="btn span12"><i class="icon-shopping-cart"></i>&nbsp;<?php echo $this->translate("Buy"); ?></a>
        <a href="#" class="btn span12"><i class="icon-random"></i>&nbsp;<?php echo $this->translate("Trade"); ?></a>
        <?php } ?>
    </div>
</div>