<?php $authorized = ($this->identity() == $this->object->user); ?>
<div class="row item gallery" style="width:700px;margin: 0 auto;" >
   
        <div class="tags-gallery" style="padding-left:125px;float:left;width:450px;">
            <h4>
                <?php echo $this->object->stuff_name; ?>
            <?php if ($this->object->state == 1) { ?>
            <label class="label label-success"><?php echo $this->translate('published'); ?></label>
            <?php } else if ($this->object->state == 0) { ?>
            <label class="label label-inverse"><?php echo $this->translate('unpublished'); ?></label>
            <?php } ?>
            </h4>
            <hr class="alt">
        </div>
    <?php if ($authorized) { ?>
    <div class="span1" style="float:right;padding-top:15px;padding-right:15px;">
        <a href="<?php echo $this->url('stuff', array( 'action' => 'edit', 
                                                        'user_id' => $this->object->user->user_id, 
                                                        'stuff_id' => $this->object->stuff_id));?>" class="btn btn-primary" style="width:50px;">
            <?php echo $this->translate('Edit'); ?>
        </a>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <a href="<?php echo $this->url('stuff', array( 'action' => 'delete', 
                                                        'user_id' => $this->object->user->user_id, 
                                                        'stuff_id' => $this->object->stuff_id));?>">
            <?php echo $this->translate('Delete'); ?>
        </a>
    </div>
    <?php } ?>
    <div style="clear:both"></div>
    <?php if ($this->object->image !== "") { ?>
    <div class="image-gallery" style="height:80px;width:80px;float:left;padding: 0 20px 0 20px;display:block;margin-top: -55px;">
        <a class="group" rel="group1" href="<?php echo $this->basePath() . '/' . $this->object->image[0]; ?>"><img src="<?php echo $this->basePath() . '/' . $this->object->image[0]; ?>"></a>
    </div>
    <?php } else { ?>
    <div class="image-gallery"><img src="holder.js/225x210/gray/text:[<?php echo $this->translate("Old Stuff Trade System"); ?>]"></div>
    <?php } ?>
    
    <div class="span4" style="width:510px">
         
     <?php echo $this->object->description ?>"     
     <br /> <br />
    </div>
     
</div>