<?php $paginator = $this->paginator; ?>
<?php if ($paginator->count() > 1) : ?>
<div class="container">
    <div class="pagination">
        <ul>
            <li><a href="?page=1">&laquo;</a></li>
            <?php for ($i = 1; $i <= $paginator->count(); $i++) { ?>
                <?php if ($i == $paginator->getCurrentPageNumber()) { ?>
            <li class="active">
                <span><?php echo $i; ?></span>
            </li>
                <?php } else { ?>
            <li>
                <a href="?page=<?php echo $i; ?>"><?php echo $i; ?></a>
            </li>
                <?php } ?>
            <?php } ?>
            <li><a href="?page=<?php echo $paginator->count(); ?>">&raquo;</a></li>
        </ul>
    </div>
</div>
<?php endif; ?>