<?php $request = $this->object; ?>
<?php //if (!$request->proposed_stuff) return; ?>
<div class="row-fluid stuff-item">
    <div class="span3 stuff-image">
        <?php if ($this->identity() == $request->requestor) { ?>
        <?php if ($request->requested_stuff->image !== "") { ?>
            <a class="group" rel="group1" href="<?php echo $this->basePath() . '/' . $request->requested_stuff->image[0]; ?>">
                <img src="<?php echo $this->basePath() . '/' . $request->requested_stuff->image[0]; ?>">
            </a>
            <?php } else { ?>
            <img src="holder.js/225x210/gray/text:[<?php echo $this->translate("Old Stuff Trade System"); ?>]">
            <?php } ?>
        <?php } else { ?>
            <?php if ($request->proposed_stuff->image !== "") { ?>
            <a class="group" rel="group1" href="<?php echo $this->basePath() . '/' . $request->proposed_stuff->image[0]; ?>">
                <img src="<?php echo $this->basePath() . '/' . $request->proposed_stuff->image[0]; ?>">
            </a>
            <?php } else { ?>
            <img src="holder.js/225x210/gray/text:[<?php echo $this->translate("Old Stuff Trade System"); ?>]">
            <?php } ?>
       <?php } ?>
    </div>
    <div class="span7 stuff-info">
        <?php if ($this->identity() == $request->requestor) { ?>
         <h4>
            <a href="<?php echo $this->stuffItemLink($request->requested_stuff->stuff_id); ?>"><?php echo $request->requested_stuff->stuff_name; ?></a>
        </h4>
        <div class="stuff-description">
            <span style="font-weight: bold"> Owner: </span>
                    <?php echo $request->requested_stuff->user->email ?></div>
        <div class="stuff-description">
            <span style="font-weight: bold"> Description: </span>
                    <?php echo $request->requested_stuff->description ?></div>        
        <?php } else { ?>
        <h4>
            <a href="<?php echo $this->stuffItemLink($request->proposed_stuff->stuff_id); ?>"><?php echo $request->proposed_stuff->stuff_name; ?></a>
        </h4>
        <div class="stuff-description">
            <span style="font-weight: bold"> Asker: </span>
                    <?php echo $request->proposed_stuff->user->email ?></div>
        <div class="stuff-description">
            <span style="font-weight: bold"> Description: </span>
                    <?php echo $request->proposed_stuff->description ?></div>
        <?php } ?>
    </div>
    <div class="span2 stuff-buttons">
          <?php if ($request->state == 0) { ?>
           <a 
               href="<?php echo $this->requestLink($request->request_id); ?>"
               class="btn btn-primary span12"> 
               <?php echo $this->translate('View'); ?>
           </a>
                <?php if ($request->requestor == $this->identity()) { ?>
                <a 
                    href="<?php echo $this->requestCancelLink($request->request_id);?>"
                    class="btn span12"> 
                    <?php echo $this->translate('Cancel'); ?>          
                </a>    
            <?php } else { ?>
                <a 
                href="<?php echo $this->requestAcceptLink($request->request_id); ?>"
                class="btn span12"> 
               <?php echo $this->translate('Accept'); ?>
           </a>
           <a 
               href="<?php echo $this->requestRejectLink($request->request_id);?>"
               class="btn span12"> 
               <?php echo $this->translate('Reject'); ?>          
           </a>  
            <?php } ?> 
           
           <?php } else if ($request->state == 1) { ?>
           <button class="btn btn-success"><?php echo $this->translate('Accepted'); ?></button>
           <?php } else if ($request->state == -1) { ?>
           <button class="btn btn-inverse"><?php echo $this->translate('Rejected'); ?></button>
           <?php } else if ($request->state == -2) { ?>
           <button class="btn btn-inverse"><?php echo $this->translate('Cancelled'); ?></button>
           <?php } ?>
        
           
        
    </div>
</div>