<div class="span3 item gallery">
    <div class="menu-gallery">
        <ul>
            <li><a href="#" rel="tooltip" data-original-title="<?php echo $this->translate('Detail'); ?>"><i class="iconbig-search"></i></a></li>
            <li><a href="#" rel="tooltip" data-original-title="<?php echo $this->translate('Buy it'); ?>"><i class="iconbig-cart"></i></a></li>
            <li><a href="#" rel="tooltip" data-original-title="<?php echo $this->translate('Request for a trade'); ?>"><i class="iconbig-2way"></i></a></li>
        </ul>
    </div>
    <?php if ($this->object->image !== "") { ?>
    <div class="image-gallery"><a class="group" rel="group1" href="<?php echo $this->basePath() . '/' . $this->object->image[0]; ?>"><img src="<?php echo $this->basePath() . '/' . $this->object->image[0]; ?>"></a></div>
    <?php } else { ?>
    <div class="image-gallery"><img src="holder.js/225x210/gray/text:[<?php echo $this->translate("Old Stuff Trade System"); ?>]"></div>
    <?php } ?>
    <div class="count-gallery">
        <ul>
            <?php if ($this->object->purpose == 'sell') { ?>
            <li><i rel="tooltip" data-title="<?php echo $this->translate('Price'); ?>" class="icon-tags"></i> <span class="price"><?php echo $this->object->price; ?></span> VND</li>
            <?php } else if ($this->object->purpose == 'trade') { ?>
            <li><i rel="tooltip" data-title="<?php echo $this->translate('Desired Stuff'); ?>" class="icon-random"></i> <?php echo $this->object->desired_stuff; ?></li>
            <?php } ?>
            <li><i rel="tooltip" data-title="<?php echo $this->translate('Category'); ?>" class="icon-bookmark"></i> <a href="#"><?php echo $this->object->category->cat_name; ?></a></li>
            <li><i rel="tooltip" data-title="<?php echo $this->translate('Owner'); ?>" class="icon-user"></i>&nbsp;<a href="#"><?php echo ($this->object->user->display_name != "") ? $this->object->user->display_name : $this->object->user->email; ?></a></li>
        </ul>
    </div>
    <div class="tags-gallery">
        <h4><?php echo $this->object->stuff_name; ?></h4>
    </div>
</div>