<?php $stuff = $this->object; ?>
<div class="span3 item gallery">
    <div class="menu-gallery">
        <ul>
            <li><a href="<?php echo $this->stuffItemLink($stuff->stuff_id); ?>" 
                   rel="tooltip" data-original-title="<?php echo $this->translate('Detail'); ?>"><i class="iconbig-search"></i></a></li>
            <li><a href="<?php echo $this->stuffBuyLink($stuff->stuff_id); ?>" 
                   rel="tooltip" data-original-title="<?php echo $this->translate('Buy it'); ?>"><i class="iconbig-cart"></i></a></li>
            <li><a href="<?php echo $this->stuffTradeLink($stuff->stuff_id); ?>"
                   rel="tooltip" data-original-title="<?php echo $this->translate('Request for a trade'); ?>"><i class="iconbig-2way"></i></a></li>
        </ul>
    </div>
    <?php if ($stuff->image !== "") { ?>
    <div class="image-gallery"><a class="group" rel="group1" href="<?php echo $this->basePath() . '/' . $stuff->image[0]; ?>"><img src="<?php echo $this->basePath() . '/' . $stuff->image[0]; ?>"></a></div>
    <?php } else { ?>
    <div class="image-gallery"><img src="holder.js/225x210/gray/text:[<?php echo $this->translate("Old Stuff Trade System"); ?>]"></div>
    <?php } ?>
    <div class="count-gallery">
        <ul>
            <?php if ($stuff->purpose == 'sell') { ?>
            <li><i rel="tooltip" data-title="<?php echo $this->translate('Price'); ?>" class="icon-tags"></i> <span class="price"><h4><?php echo $stuff->price; ?></h4></span> VND</li>
            <?php } else if ($stuff->purpose == 'trade') { ?>
            <li><i rel="tooltip" data-title="<?php echo $this->translate('Desired Stuff'); ?>" class="icon-random"></i> <h4><?php echo $stuff->desired_stuff; ?></h4></li>
            <?php } ?>
            <li><i rel="tooltip" data-title="<?php echo $this->translate('Category'); ?>" class="icon-bookmark"></i>
                <form method="POST" class="form-link">
                    <button class="btn btn-link" type="submit"><?php echo $stuff->category->cat_name; ?></button>
                    <input type="hidden" name="filter_category" value="<?php echo $stuff->category->cat_id; ?>   " />
                </form>
            </li>
            <li><i rel="tooltip" data-title="<?php echo $this->translate('Owner'); ?>" class="icon-user"></i>&nbsp;<a href="<?php echo $this->stuffUserLink($stuff->user->user_id); ?>"><?php echo ($stuff->user->display_name != "") ? $stuff->user->display_name : $stuff->user->email; ?></a></li>
        </ul>
    </div>
    <div class="tags-gallery">
        <h4><a href="<?php echo $this->stuffItemLink($stuff->stuff_id); ?>"><?php echo $stuff->stuff_name; ?></a></h4>
    </div>
</div>