<?php $stuff = $this->object; ?>
<?php $authorized = ($this->identity() == $stuff->user); ?>
<div class="row-fluid stuff-item">
    <div class="span3 stuff-image">
        <?php if ($stuff->image !== "") { ?>
        <a class="group" rel="group1" href="<?php echo $this->basePath() . '/' . $stuff->image[0]; ?>">
            <img src="<?php echo $this->basePath() . '/' . $stuff->image[0]; ?>">
        </a>
        <?php } else { ?>
        <img src="holder.js/225x210/gray/text:[<?php echo $this->translate("Old Stuff Trade System"); ?>]">
        <?php } ?>
    </div>
    <div class="span7 stuff-info">
        <h4>
            <a href="<?php echo $this->stuffItemLink($stuff->stuff_id); ?>"><?php echo $stuff->stuff_name; ?></a>
            <?php if ($authorized) { 
                echo $this->partial('stuff/partial/state-badge.phtml', array('state' => $stuff->state));
            } ?>
        </h4>
        <ul class="stuff-value">
            <?php if ($stuff->purpose == 'sell') { ?>
            <li><i rel="tooltip" data-title="<?php echo $this->translate('Price'); ?>" class="icon-tags"></i> <span class="price"><h4><?php echo $stuff->price; ?></h4></span> VND</li>
            <?php } else if ($stuff->purpose == 'trade') { ?>
            <li><i rel="tooltip" data-title="<?php echo $this->translate('Desired Stuff'); ?>" class="icon-random"></i> <h4><?php echo $stuff->desired_stuff; ?></h4></li>
            <?php } ?>
            <li><i rel="tooltip" data-title="<?php echo $this->translate('Category'); ?>" class="icon-bookmark"></i>
                <form method="POST" class="form-link">
                    <button class="btn btn-link" type="submit"><?php echo $stuff->category->cat_name; ?></button>
                    <input type="hidden" name="filter_category" value="<?php echo $stuff->category->cat_id; ?>   " />
                </form>
            </li>
        </ul>
        <div class="stuff-description"><?php echo $stuff->description ?></div>
    </div>
    <div class="span2 stuff-buttons">
        <?php if ($authorized) { ?>
        <a href="<?php echo $this->stuffEditLink($stuff->stuff_id);?>" 
            class="btn btn-primary span12">
            <?php echo $this->translate('Edit'); ?>
        </a>
        <a href="<?php echo $this->stuffDeleteLink($stuff->stuff_id);?>"
            class="btn btn-link span12 delete-link">
            <?php echo $this->translate('Delete'); ?>
        </a>
        <?php } else { ?>
        <a href="#" class="btn span12 btn-success"><i class="icon-shopping-cart"></i>&nbsp;<?php echo $this->translate("Buy"); ?></a>
        <a href="#" class="btn span12 btn-info"><i class="icon-random"></i>&nbsp;<?php echo $this->translate("Trade"); ?></a>
        <?php } ?>
    </div>
</div>