<div class="row">
    <div class="span3">
        <div class="nav-headers">
            <h4>Find some interesting stuffs or submit your own things. You will never know what you can find here!</h4>
        </div>
        <ul class="nav nav-tabs nav-stacked">
            <li class="active"><a href="#">Books</a></li>
            <li><a href="#">Clothes</a></li>
            <li><a href="#">Electronics</a></li>
            <li><a href="#">Jewelry</a></li>
            <li><a href="#">Toys</a></li>
        </ul>
    </div>
</div>